services:

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - global-network

  backend-server:
    container_name: backend-server
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-server:latest
    depends_on:
      - db
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    networks:
      - global-network

networks:
  global-network:
    driver: bridge